### ISSUE TITLE
поддержка соответствий (match) из питон 3.10

### ISSUE THREAD

**Issue by evtn** [evtn/birp#2]
надо очень......
когда-нибудь сделаю

**Comment by tailsjs** [comment]
делаеш?

**Comment by evtn** [comment]
что-то не делаю..............

**Comment by tailsjs** [comment]
а чо за соответствия вообще

**Comment by evtn** [comment]
соответствия (match)

**Comment by tailsjs** [comment]
[PEP 634](https://www.python.org/dev/peps/pep-0634), Structural Pattern Matching: Specification

[PEP 635](https://www.python.org/dev/peps/pep-0635), Structural Pattern Matching: Motivation and Rationale

[PEP 636](https://www.python.org/dev/peps/pep-0636), Structural Pattern Matching: Tutorial штоли

**Comment by evtn** [comment]
Да, [PEP 634](https://www.python.org/dev/peps/pep-0634), Structural Pattern Matching: Specification

[PEP 635](https://www.python.org/dev/peps/pep-0635), Structural Pattern Matching: Motivation and Rationale

[PEP 636](https://www.python.org/dev/peps/pep-0636), Structural Pattern Matching: Tutorial

**Comment by tailsjs** [comment]
понял. значит [PEP 634](https://www.python.org/dev/peps/pep-0634), Structural Pattern Matching: Specification

[PEP 635](https://www.python.org/dev/peps/pep-0635), Structural Pattern Matching: Motivation and Rationale

[PEP 636](https://www.python.org/dev/peps/pep-0636), Structural Pattern Matching: Tutorial это то что надо

**Comment by evtn** [comment]
Я считаю [PEP 634](https://www.python.org/dev/peps/pep-0634), Structural Pattern Matching: Specification

[PEP 635](https://www.python.org/dev/peps/pep-0635), Structural Pattern Matching: Motivation and Rationale

[PEP 636](https://www.python.org/dev/peps/pep-0636), Structural Pattern Matching: Tutorial это прорыв

**Comment by tailsjs** [comment]
согласен. [PEP 634](https://www.python.org/dev/peps/pep-0634), Structural Pattern Matching: Specification

[PEP 635](https://www.python.org/dev/peps/pep-0635), Structural Pattern Matching: Motivation and Rationale

[PEP 636](https://www.python.org/dev/peps/pep-0636), Structural Pattern Matching: Tutorial революционны

**Comment by nitreojs** [comment]
ну чё

**Comment by evtn** [comment]
> ну чё

когда-нибудь позже сделаю [PEP 634](https://www.python.org/dev/peps/pep-0634), Structural Pattern Matching: Specification

[PEP 635](https://www.python.org/dev/peps/pep-0635), Structural Pattern Matching: Motivation and Rationale

[PEP 636](https://www.python.org/dev/peps/pep-0636), Structural Pattern Matching: Tutorial

**Comment by evtn** [comment]
Всем спасибо, [PEP 634](https://www.python.org/dev/peps/pep-0634), Structural Pattern Matching: Specification

[PEP 635](https://www.python.org/dev/peps/pep-0635), Structural Pattern Matching: Motivation and Rationale

[PEP 636](https://www.python.org/dev/peps/pep-0636), Structural Pattern Matching: Tutorial [добавлены](https://github.com/evtn/birp/commit/72e5203022ff9b80f9af436d04c9db27e600e5ac)

**Comment by tailsjs** [comment]
https://www.youtube.com/watch?v=BVMt2sHcfcM

**Comment by tailsjs** [comment]
https://user-images.githubusercontent.com/49571184/174493798-85cf7de0-d9d7-4c3d-84ab-df360c6de620.mp4
